sudo: false
language: node_js
node_js:
- "stable"
addons:
  chrome: stable
before_script:
- psql -c 'drop database if exists store;' -U postgres
- psql -c 'create database store;' -U postgres
- psql -c 'create database store;' -U postgres
- psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
script:
- npm test
- npm run coverage
after_success: npm run coverage
