sudo: false
language: node_js
node_js:
- "stable"
before_install:
- export PATH="$HOME:$PATH"
before_script:
- psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
- psql -c 'drop database if exists store;' -U postgres
- psql -c 'create database store;' -U postgres
script:
- npm test
- npm run coverage
after_success: npm run coverage
